#!/bin/sh
# s6 service: copy this directory to your s6 scan directory.
#
# Install (s6-rc example):
#   cp -r contrib/s6 /etc/s6/sv/ulatencyd
#   s6-rc-bundle-update add default ulatencyd
#   s6-rc -u change ulatencyd

# Use s6-notifyoncheck to forward sd_notify READY=1 to s6.
exec s6-notifyoncheck -d -s 100 -w 200 -n 1 \
    /usr/sbin/ulatencyd
